# Generated by Django 5.2.8 on 2025-11-22 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                ("BillID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "TotalBeforeDiscount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "DiscountAmount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("TaxAmount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("PaymentMethod", models.CharField(max_length=50)),
                ("PaymentDate", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                ("BranchID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=100)),
                ("Location", models.CharField(max_length=200)),
                ("Contact", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("CustomerID", models.AutoField(primary_key=True, serialize=False)),
                ("FirstName", models.CharField(max_length=50)),
                ("LastName", models.CharField(max_length=50)),
                ("Contact", models.CharField(max_length=20)),
                ("Email", models.CharField(max_length=100)),
                ("LoyaltyPoints", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                ("DiscountID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=50)),
                ("Description", models.TextField()),
                ("Percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("StartDate", models.DateField()),
                ("EndDate", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("FeedbackID", models.AutoField(primary_key=True, serialize=False)),
                ("Rating", models.IntegerField()),
                ("Comment", models.TextField()),
                ("Date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="FoodChallenge",
            fields=[
                ("ChallengeID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=100)),
                ("Description", models.TextField()),
                ("Reward", models.CharField(max_length=100)),
                ("StartDate", models.DateField()),
                ("EndDate", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                ("MenuItemID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=100)),
                ("Price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Category", models.CharField(max_length=50)),
                ("Availability", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("OrderID", models.AutoField(primary_key=True, serialize=False)),
                ("OrderDate", models.DateTimeField()),
                ("Status", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("ReservationID", models.AutoField(primary_key=True, serialize=False)),
                ("ReservationDateTime", models.DateTimeField()),
                ("NumPeople", models.IntegerField()),
                ("TableNumber", models.IntegerField()),
                ("Status", models.CharField(max_length=50)),
                ("Confirmed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                ("StaffID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=100)),
                ("Role", models.CharField(max_length=50)),
                ("Salary", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "Email",
                    models.EmailField(
                        default="staff@example.com", max_length=254, unique=True
                    ),
                ),
                (
                    "Password",
                    models.CharField(default="hashed_password", max_length=255),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("SupplierID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=100)),
                ("Contact", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="BillComputation",
            fields=[
                (
                    "BillID",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="api.bill",
                    ),
                ),
                ("TotalAmount", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name="bill",
            name="OrderID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.order"
            ),
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                ("ItemID", models.AutoField(primary_key=True, serialize=False)),
                ("ItemName", models.CharField(max_length=100)),
                ("QuantityAvailable", models.IntegerField()),
                ("ReorderLevel", models.IntegerField()),
                (
                    "SupplierID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.supplier"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Applies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "BillID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.bill"
                    ),
                ),
                (
                    "DiscountID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.discount"
                    ),
                ),
            ],
            options={
                "unique_together": {("BillID", "DiscountID")},
            },
        ),
        migrations.CreateModel(
            name="ChallengeParticipation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CompletionDate", models.DateField(blank=True, null=True)),
                ("Status", models.CharField(max_length=50)),
                (
                    "CustomerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.customer"
                    ),
                ),
                (
                    "ChallengeID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.foodchallenge",
                    ),
                ),
            ],
            options={
                "unique_together": {("CustomerID", "ChallengeID")},
            },
        ),
        migrations.CreateModel(
            name="FeedbackOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "FeedbackID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.feedback"
                    ),
                ),
                (
                    "OrderID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.order"
                    ),
                ),
            ],
            options={
                "unique_together": {("FeedbackID", "OrderID")},
            },
        ),
        migrations.CreateModel(
            name="OrderCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "CustomerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.customer"
                    ),
                ),
                (
                    "OrderID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.order"
                    ),
                ),
            ],
            options={
                "unique_together": {("OrderID", "CustomerID")},
            },
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Quantity", models.IntegerField()),
                (
                    "MenuItemID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.menuitem"
                    ),
                ),
                (
                    "OrderID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.order"
                    ),
                ),
            ],
            options={
                "unique_together": {("OrderID", "MenuItemID")},
            },
        ),
        migrations.CreateModel(
            name="ReservationCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "CustomerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.customer"
                    ),
                ),
                (
                    "ReservationID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.reservation",
                    ),
                ),
            ],
            options={
                "unique_together": {("ReservationID", "CustomerID")},
            },
        ),
        migrations.CreateModel(
            name="OrderStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "OrderID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.order"
                    ),
                ),
                (
                    "StaffID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.staff"
                    ),
                ),
            ],
            options={
                "unique_together": {("OrderID", "StaffID")},
            },
        ),
        migrations.CreateModel(
            name="WorksAt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "BranchID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.branch"
                    ),
                ),
                (
                    "StaffID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.staff"
                    ),
                ),
            ],
            options={
                "unique_together": {("StaffID", "BranchID")},
            },
        ),
    ]
